ecommerce/myapp/urls.py
from django.urls import path
from myapp.views import index
from myapp.views import customer_details
app_name='myapp'

urlpatterns = [
 path('',index,name='index'),
 path('customer_details/',customer_details,name='customer_details'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('registration.backends.default.urls')),
    path('', include('myapp.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    

myapp/urls.py
from django.urls import path
from myapp.views import products,detail,cart_view,order,return_view,cancel_view,review,send_email,category
app_name='myapp'

urlpatterns = [
path('',category,name='category'),
path('products/<int:product_id>/<slug:slug>',products,name='products'),
path('<int:product_id>/<slug:slug>',detail,name='detail'),
path('cart/',cart_view,name='cart_view'),
path('order/',order,name='order'),
path('success/',return_view,name='return_view'),
path('cancel/',cancel_view,name='cancel_view'),
path('<int:product_id>/<slug:slug>/review/',review,name='review'),
path('sendmail/',send_email,name='send_email'),
]

urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce/myapp/models.py
from django.db import models

class Product(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField()
    slug=models.SlugField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    img=models.ImageField(upload_to='')
    
    def __str__(self):
        return self.title

myapp/models.py
from django.db import models
from django .contrib.auth.models import User
class Category(models.Model):
    title=models.CharField(max_length=50)
    img=models.ImageField(upload_to='')
    slug=models.SlugField()
    def __str__(self):
        return self.title
class Product(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField()
    slug=models.SlugField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    img=models.ImageField(upload_to='')
    product_available=models.BooleanField(default=False)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,default=1)
    def __str__(self):
        return self.title 
class Cart(models.Model):
    cart_id=models.CharField(max_length=100)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    quantity=models.IntegerField()
    timestamp=models.DateTimeField(auto_now=True)
    product=models.ForeignKey(Product,on_delete=models.PROTECT)
    def _str_(self):
        return self.product.title 
    def update_quantity(self,quantity):
        self.quantity+=quantity
        self.save()
    def total(self):
        return self.quantity*self.price
class Buy(models.Model):
    product=models.ForeignKey(Product,on_delete=models.PROTECT)
    quantity=models.IntegerField()
    price=models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return self.product.title+'_'+str(self.id)

class TimeStamp(models.Model):
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	user = models.ForeignKey(User,on_delete = models.CASCADE)

	class Meta:
		abstract = True

class Review(TimeStamp):
	post = models.ForeignKey(Product,on_delete = models.CASCADE)
	review = models.TextField()

	def __str__(self):
		return self.review 

myapp/forms.py
from django import forms
from myapp.models import Review

class CartForm(forms.Form):
    quantity=forms.IntegerField(initial='1')
    product_id=forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self,request,*args,**kwargs):
        self.request=request
        super(CartForm,self).__init__(*args,**kwargs)   
class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		fields = ['review']

        

ecommerce/myapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from myapp.models import Product
# Create your views here.
@login_required
def index(request):
    p=Product.objects.all()
    context={'p':p}
    return render(request,'index.html',context)

myapp/views.py
from django.shortcuts import  get_object_or_404,render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from myapp.models import Product,Cart,Buy,Review,Category
from myapp.forms import CartForm,ReviewForm
from myapp.myapp import *
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from paypal.standard.forms import PayPalPaymentsForm


# Create your views here.

def category(request):
    c= Category.objects.all()
    context={'c':c}
    print(c)
    return render(request,'categories.html',context)
def products(request,product_id,slug):
    p=Product.objects.filter(category=product_id)
    if request.GET.get('q'):
        query=request.GET.get('q')
        p=Product.objects.filter(title__icontains=query)
    context={'p':p}
    return render(request,'index.html',context)
def index(request):
    p=Product.objects.all()
    if request.GET.get('q'):
        query=request.GET.get('q')
        p=Product.objects.filter(title__contains=query)
    context={'p':p}
    return render(request,'index.html',context)
def detail(request,product_id,slug):
    d=Product.objects.get(id=product_id)
    if request.method=="POST":
        f=CartForm(request,request.POST)
        if f.is_valid():
            request.form_data=f.cleaned_data
            add_to_cart(request)
            return redirect('myapp:cart_view')

    f=CartForm(request,initial={'product_id':product_id})
    context={'d':d,'f':f}
    return render(request,'detail.html',context)
def cart_view(request):
    if request.method=="POST" and request.POST.get('delete')=='Delete':
        item_id=request.POST.get('item_id')
        cd=Cart.objects.get(id=item_id)
        cd.delete()
    c=get_cart(request)
    t=total_(request)
    co=item_count(request)
    context={'c':c,'t':t}
    return render(request,'cart.html',context)
def order(request):
    # What you want the button to do.
    items=get_cart(request)
    for i in items:
        b=Buy(product_id=i.product_id,quantity=i.quantity,price=i.price)
        b.save()
    paypal_dict = {
        "business": "sb-zsqow28539424@business.example.com",
        "amount": total_(request),
        "item_name": cart_id(request),
        "invoice": str(uuid.uuid4()),
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('myapp:return_view')),
        "cancel_return": request.build_absolute_uri(reverse('myapp:cancel_view')),
        "custom": "premium_plan",  # Custom command to correlate to some function later (optional)
    }

    # Create the instance.
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form,"items":items,"total":total_(request)}
    return render(request, "order.html", context)
def return_view(request):
    return render(request,'transraction.html')
def cancel_view(request):
    return HttpResponse('Transaction Cancelled')        
def create_rewiew(request):
    if request.method=='POST':
        form=ReviewForm(request.POST)
        if form.is_valid():
            rewiew=form.save(commit=False)
            rewiew.user=request.user
            rewiew.save()
            return redirect('product_detail',pk=review.product.pk)
        else:
            form=ReviewForm()
            return render(request,'create_review.html',{'form':form})
def review(request,product_id,slug):
    d=Product.objects.get(id=product_id)
    reviews = Review.objects.filter(post_id = product_id)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.cleaned_data['review']
            c = Review(post_id = product_id,review = review,user = request.user)
            c.save()

        else:
            form = ReviewForm()
        return render(request, 'review.html', {'d':d,'form': form,'reviews':reviews})

from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect

def send_email(request):
    subject = request.POST.get("subject", "Hi Pavani")
    message = request.POST.get("message", "otp is 25812")
    from_email = request.POST.get("dannesanjana6@gamil.com")
    if subject and message and from_email:
        try:
            send_mail(subject, message, from_email, ["malavathpavani29@gmail.com"])
        except BadHeaderError:
            return HttpResponse("Invalid header found.")
        return HttpResponseRedirect("Mail sent to pk")
    else:
        # In reality we'd use a form class
        # to get proper validation errors.
        return HttpResponse("Make sure all fields are entered and valid.")

myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, 
    initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</head>
<body>
  
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: cadetblue">
    <a class="navbar-brand" href="{% url 'myapp:category' %}">Ecommerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="http://127.0.0.1:8000/products/5/Jewellery">Jewellery<span class="sr-only">(current)</span></a>
            </li>
            </ul>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="http://127.0.0.1:8000/products/6/shirts"><span class="sr-only">(current)</span></a>
                </li>
                </ul>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="http://127.0.0.1:8000/products/12/Toyes">Toys<span class="sr-only">(current)</span></a>
                    </li>
                    </ul>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                      <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                          <a class="nav-link" href="http://127.0.0.1:8000/products/7/kurthis">kurthis<span class="sr-only">(current)</span></a>
                        </li>
                        </ul>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                          <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                              <a class="nav-link" href="http://127.0.0.1:8000/products/8/slippers">slippers<span class="sr-only">(current)</span></a>
                            </li>
                            </ul>
                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                              <ul class="navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="http://127.0.0.1:8000/products/11/Electricaldevices">Electricaldevices<span class="sr-only">(current)</span></a>
                                </li>
                                </ul>
         
                                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                  <ul class="navbar-nav mr-auto">
                                    <li class="nav-item active">
                                      <a class="nav-link" href="http://127.0.0.1:8000/products/6/shirts">shirtss<span class="sr-only">(current)</span></a>
                                    </li>
                                    </ul>
                                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                      <ul class="navbar-nav mr-auto">
                                        <li class="nav-item active">
                                          <a class="nav-link" href="http://127.0.0.1:8000/products/13/FORNITURE">furniture<span class="sr-only">(current)</span></a>
                                        </li>
                                        </ul>
               
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" name='q' value="{{request.GET.q}}" placeholder="Search" aria-label="Search">&nbsp;&nbsp;
          </form>
          {{user}}&nbsp;&nbsp;&nbsp;&nbsp;
          {% if not user.is_authenticated %} 
          <a class="btn btn-primary" href="{% url 'auth_login' %}">Login</a>&nbsp;&nbsp;
          <a class="btn btn-primary" href="{% url 'registration_register' %}">Register</a>&nbsp;&nbsp;
          {% else %}
          <a class="btn btn-primary" href="{% url 'auth_logout' %}">Logout</a>&nbsp;&nbsp;
          <a href="{% url 'myapp:cart_view'%}"class="btn btn-outline-success my-2 my-sm-0"> 🛒 Cart</a>&nbsp;&nbsp;&nbsp;&nbsp;

          {% endif %}
          <a  class="btn btn-outline-secondary my-2 my-sm-0"  href="/admin/">Staff</a>&nbsp;&nbsp;
        </div>
      </nav>
    <br>
    
{% block content %}

{% endblock %}
</div>

</body>
</html>

myapp/templates/cart.html
{% extends 'base.html' %}
{% block content %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">product</th>
        <th scope="col">price</th>
        <th scope="col">quantity</th>
        <th scope="col">Total Cost</th>

      </tr>
    </thead>
    <tbody>
    {% for i in c %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{i.product}}</td>
        <td>{{i.price}}</td>
        <td>{{i.quantity}}</td>
        <td>{{i.total}}</td>
        <td>
        <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{i.id}}">
            <input class="btn btn-danger" type="submit" name="delete" value="Delete">
        </form>
      </td>
      </tr>
      {% endfor %}
    </tbody>  
  </table><br>
  Total:₹{{t}}<br>
  <br>
  <a class="btn btn-info" href="{% url 'myapp:order' %}">Order</a>
  &nbsp;&nbsp;&nbsp;
  <a class="btn btn-info" href="{% url 'myapp:category' %}">Back/Continue</a>
{% endblock %}

myapp/templates/categories.html
{% extends 'base.html' %}

{% block content %}
<h1><center>ECOMMERCE</center></h1>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://www.newgenmax.com/wp-content/uploads/2018/07/Ecommerce-Banner-1.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://www.webworldtechnologies.in/images/shopping-cart-solutions-bottom-banner.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://www.insidesoftwares.com/images/ecommerce-website-banner.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-target="#carouselExampleIndicators" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-target="#carouselExampleIndicators" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </button>
</div>

<center><h1>Products By Category</h1></center>
<div class="w3-container">
  <div class="row">
      {% for product in c %}
  <div class="col-md-3 mb-3">
      <div class="card">
          <center><img src="{{ product.img.url }}" class="card-img-top img-fluid rounded" alt="{{ product.title }}" style="max-width: 200px; height: 250px; object-fit: cover;"></center>
              <div class="card-body">
                  <h5 class="card-title">
<a href="{% url 'myapp:products' product.id product.slug %}">{{ product.title }}</a>

      </h5>
      </div>
      </div>
  </div>
{% endfor %}
</div>
</div></div>
<div class="card primary card-expand-lg bg-info">
  <br> <center><h1>CONTACT US</h1></center>
  <h5><i class="material-icons">place:-</i><a href="https://www.google.com/maps/place/Parvathaneni+Brahmayya+Siddhartha+college+of+Arts+%26+Science/@16.5055349,80.6469164,17z/data=!4m15!1m8!3m7!1s0x3a35fab6cd09a89b:0xd33167f96ffe60b7!2sGJ4X%2B6Q9+PB+Siddhartha+College+Gym,+Mogalrajapuram,+Siddhartha+Nagar,+Benz+Circle,+Vijayawada,+Andhra+Pradesh+520010!3b1!8m2!3d16.5055298!4d80.6494913!16s%2Fg%2F1hhj1fh8g!3m5!1s0x3a35fab12587c72b:0x20aec0bac504143c!8m2!3d16.5050802!4d80.648373!16s%2Fg%2F1tzvtzmq?entry=ttu" class="text-dark">PARVATHANENI BRHAMAYYA SIDDHARTHA COLLEGE OF ARTS AND SCINCE</a></h5>
  <h5><i class="material-icons">local_phone:-</i>0866-2475966</h5>
  <h5><i class="material-icons">mail:-</i>pbs_college@hotmail.com</h5>
  <CENTER><h2>FOLLOW US</h2></CENTER>
  <h4> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://twitter.com/i/flow/login?redirect_after_login=%2FPBSiddharthaco2" class="text-dark"  style='font-size:24px'><i class="fa fa-twitter"></i></a>&nbsp;&nbsp;<a href="https://www.facebook.com/pbsiddharthaclg/" class="text-dark" style='font-size:24px'><i class="material-icons" class="text-dark">facebook</i></a>&nbsp;&nbsp;<a href="https://www.instagram.com/pbsiddharthacollege/" class="text-dark" style='font-size:24px'><i class="fa fa-instagram"></i></a>&nbsp;&nbsp;<a href="https://www.linkedin.com/school/parvathaneni-brahmayya-siddhartha-college-of-arts-&-science/?originalSubdomain=in" class="text-dark" style='font-size:24px'><i class="fa fa-linkedin-square"></i></a></h4>
<br>
<br>
</div>
{% endblock %}
</div>

myapp/templates/customer.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-6">
    <b>{{d.title}}</b><br>
    {{d.Full name}}<br>
    {{d.Last name}}<br>
    {{d.Phone}}<br>
    {{d.Email}}<br>
    {{d.password}}<br>
    </div>
    <form action="{% url 'myapp:customer' c.id c.slug %}" method="post">
        {% csrf_token %}
        {{ f }}
        <input type="submit" value="Add to Cart">
    </form>
    </div>
    <input type="submit" >
</form>
{% endblock %}

myapp/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<div class="row">
<div class="col-md-6">
   <h2> {{d.title}}</h2><br> 
        {{d.description}}<br><br>
       <b> ₹{{d.price}}</b><br>
</div>
        <div class="col-md-6">
       <br> <img src="{{d.img.url}}" widt="400" height="500" >
        </div>
    </div>
{% if  user.is_authenticated %}
<form action="{% url 'myapp:detail' d.id d.slug%}" method="post">
    {% csrf_token %}
    {{ f }}
    <input type="submit" value="Add to Cart">
</form>
<center><form action="{% url 'myapp:review' d.id d.slug %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Add to Reviews">
</form></center>
{% else %}
<p>please login if you want do add to cart or to add reviews</p>
{% endif %}
{% endblock %}
</div></div>

myapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="row">
      {% for i in p %}
      <div class="col-md-3 mb-3">
        <div class="card">
              <img src="{{i.img.url}}" width="150" height="150"><br>
              <div class="card-body">
                {% if i.product_available is True %}
                </a><h5 class="card-title"><a href="{% url 'myapp:detail' i.id i.slug %}"><b>{{i.title}}</b></a></h5>
                ⟨₹⟩{{i.price}}
                <br><br><br>
                {% else %}   
                <b>Out Of Stock</b>
                {% endif %}
              </div>
            </div> 
          </div>
  
      {% endfor %} <br><br> 
        </div>


  </div>
  
  {% endblock %}
</div>

myapp/templates/order.html
{% extends 'base.html' %}
{% block content %}
<b>Cart:</b><br>
{% for i in items %}
{{i.product}}<br>
{% endfor %}
Pay: {{total}}
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}
{% endblock %}

myapp/templates/page.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    {% for i in p %}
    <div class="col-md-6">
      <a href="{% url 'myapp:detail' i.id i.slug %}"><b>{{i.title}}</b></a><br>
      <img src="{{i.img.url}}" width=300 height=300 alt=""><br>
      ₹{{i.price}}
      <br><br>
      <style>
        body{
          background-color:lightcyan;

        }
      </style>
    </div>
    {% endfor %}
</div>
{% endblock %}

myapp/templates/review.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-6">
    <b>{{d.title}}</b><br>
    {{d.description}}<br>
    {{d.price}}<br>
    </div>
    <div class="col-md-6">
        <img src="{{d.img.url}}" widt=400 height="500">
    </div>

</div> 

<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" class ="btn btn-primary">
	</form>

	</div>

</div>
	<br><br><br>
	<h6>Reviews:</h6>
    
    {% for i in reviews %}

    {{forloop.counter}} - {{i.review}} <br>
    at {{i.created_at}} by {{i.user}} <br>

    {% endfor %}

</div>


{% endblock %}

myapp/templates/transaction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><br><br><br><br>
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7fLGbTFZKIDyOeXJFQ3C16nwyt-qlL4iKyA&usqp=CAU" width="70" height="70">
    <h1>Order Placed</h1>
</center>
</body>
</html>

myapp/templates/transraction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><br><br><br><br>
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7fLGbTFZKIDyOeXJFQ3C16nwyt-qlL4iKyA&usqp=CAU" width="70" height="70">
    <h1>Order Placed</h1>
    </center>
</body>
</html>